### ISSUE TITLE
2020-03-12 CSV 

### ISSUE THREAD

**Issue by claudiasv** [RamiKrispin/coronavirus-csv#5]
Hi, 

I'm a student from Spain using your dataset. 
Can it be possible for countries like Italy and Spain that in 2020-03-12 the number of confirmed cases is 0? 

Thank you very much!

**Comment by steve-soundings** [comment]
Hi Claudia:

Take a close look at the data. It seems that the cases for  2020-03-12 are rolled into the 2020-03-13 numbers. Here's Italy, for example:
![Rplot](https://user-images.githubusercontent.com/59899522/76704434-5f282d80-66af-11ea-92c1-e9b2ce7d752d.png)

**Comment by claudiasv** [comment]
True, thank you!!

**Comment by pbhogale** [comment]
Indeed, the cases have been rolled into 13th March, could this be fixed ? is there any good reason for this ?
