### ISSUE TITLE
Missing "Recovered" Type in the update

### ISSUE THREAD

**Issue by SaiRamakuru** [RamiKrispin/coronavirus-csv#6]
Hello Rami, 

The latest update is missing Type=Recovered (all the entries).

![image](https://user-images.githubusercontent.com/9664057/77393349-d7a38400-6d6a-11ea-862a-6de75e3dc231.png)

**Comment by RamiKrispin** [comment]
Hi @SaiRamakuru, yes, the recovered cases were removed due to changes in the raw data. Please view the following issues:

https://github.com/RamiKrispin/coronavirus/issues/32

https://github.com/CSSEGISandData/COVID-19/issues/1250

**Comment by RamiKrispin** [comment]
@SaiRamakuru Please note that the recovered cases are now available on the dataset
