### ISSUE TITLE
correction of a value 

### ISSUE THREAD

**Issue by science4u** [RamiKrispin/coronavirus-csv#8]
Hi,
I'm new here in Github and learning R (thanks for your nice work, helped me a lot), so probably I could fix it after pull the data. 
Sorry if I'm not writing in the right place (here?).
 
I think there is a small mistake in the data of the Excel file  (line 5015) and in the correspondent csv file. The number I supose is correct but has a negative signal (-6526). It's for newly confirmed cases of France in the day 14-04-2020 (noticed that when I ploted).
Can you help?

Thanks.

**Comment by RamiKrispin** [comment]
Hi @science4u 

Not sure why you are getting this value, on my side, this is what I see:
![image](https://user-images.githubusercontent.com/12760966/79704851-3ecc2f80-8268-11ea-88d5-6f506ed00ed6.png)

Could you please repull the file and let me know if you are still getting this value?

Thanks,
Rami

**Comment by science4u** [comment]
Hi,

Now it's ok.
Thanks.
Humberto
